id: nginx
name: Nginx Web Server
description: Nginx web server with SSL support and configurable volumes
category: web-servers
createdAt: "2024-01-15T00:00:00.000Z"
updatedAt: "2024-01-15T00:00:00.000Z"
