services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    # if you're using arm64, use the following line instead
    # image: mcr.microsoft.com/azure-sql-edge
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    volumes:
      - sql-server-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sql-server-data:
